// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJuzkN3K9NlTio06c4_NqC2XxdKRdnxBk',
    appId: '1:787133655801:web:84e52698a5d8de9a991028',
    messagingSenderId: '787133655801',
    projectId: 'starter-project-symmetry-avn',
    authDomain: 'starter-project-symmetry-avn.firebaseapp.com',
    storageBucket: 'starter-project-symmetry-avn.firebasestorage.app',
    measurementId: 'G-C1CTQ9L8M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzgc47zXI8ZVNXNXY10yRpqcYY1ck8zl8',
    appId: '1:787133655801:android:cde1754dd23fa93a991028',
    messagingSenderId: '787133655801',
    projectId: 'starter-project-symmetry-avn',
    storageBucket: 'starter-project-symmetry-avn.firebasestorage.app',
  );

}